#数据库连接 mysql
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/rs_report?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=GMT%2B8
#    username: root
#    password: 12345678
#    driver-class-name: com.mysql.cj.jdbc.Driver
spring:
  datasource:
    url: jdbc:sqlite::resource:rsreport.sqlite3
    username:
    password:
    driver-class-name: org.sqlite.JDBC
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mybatis/*.xml
#logging:
#  config: classpath:log4j.properties